name: App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: front-end/package-lock.json  # <-- Explicitly set the path

    - run: npm ci
      working-directory: front-end  # <-- Set working directory

    # - run: npm run build --if-present
    #   working-directory: front-end  # Uncomment when needed

    # - run: npm test
    #   working-directory: front-end  # Uncomment when needed
